all: StockData.class

StockData.class:
	javac -Xlint -cp /Users/aakritprasad/Desktop/JavaLibs/hibernate-release-4.3.1.Final/lib/required/hibernate-core-4.3.1.Final.jar stocks/*.java

clean:
	rm stocks/*.class
